language: cpp

os:
  - linux
sudo: required

addons:
  apt:
    packages:
      - libwww-perl

compiler:
  - gcc
  - clang
  
env:
  global:
    - DSVERIFIER_HOME=$PWD
   
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test  && sudo apt-get -qq update && sudo apt-get -qq install g++-4.9 gcc-4.9 && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 60 && sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60
  - gcc --version
  - sudo apt-get -qq update
  - sudo apt-get install libeigen3-dev -y
  - sudo apt-get install libboost-dev -y
  - export PATH=$PATH:$DSVERIFIER_HOME
  
install:
  - chmod a+x regression/run-all.sh
  - make bmc-download
  - chmod -R a+x model-checker/

script:
  - make && cd regression/ && ./run-all.sh
