language: cpp

os:
  - linux
sudo: required

addons:
  apt:
    packages:
      - libwww-perl
      - libeigen3-dev
      - libboost-dev
      - eigen3-static
      - eigen3
      - eigen3-devel

compiler:
  - gcc
  - clang

before_install:
  - if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ] ; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get -qq update && sudo apt-get -qq install g++-4.9 gcc-4.9 && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90 && sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 90 ; fi

install:
  - chmod a+x regression/cbmc/closed-loop/test.pl
  - make dsverifier

#script:
 # - make CXXFLAGS="-Wall -O2 -g -Werror -Wno-deprecated-register -pedantic -Wno-sign-compare" -j2 && cd ../regression/cbmc/closed-loop && make

