language: cpp

matrix:
  include:
    # Ubuntu Linux with glibc using g++-5
    - os: linux
      sudo: false
      compiler: gcc
      cache: ccache
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libwww-perl
            - g++-5
            - libubsan0
            - libeigen3-dev
            - libboost-dev

  allow_failures:
    - env: NAME="CPP-LINT"
      install:
      script: scripts/travis_lint.sh
before_cache:


compiler:
  - gcc
  
env:
  global:
    - DSVERIFIER_HOME=$PWD
   
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test  && sudo apt-get -qq update && sudo apt-get -qq install g++-4.9 gcc-4.9 && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 60 && sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60
  - gcc --version
  - sudo apt-get -qq update
  - sudo apt-get install libeigen3-dev -y
- sudo apt-get install libboost-dev -y
  - gcc --version
  - export PATH=$PATH:$DSVERIFIER_HOME
  
install:
  - chmod a+x regression/run-all.sh
  - make bmc-download
  - chmod -R a+x model-checker/

script:
  - make && cd regression/ && ./run-all.sh
  
before_cache:
  - ccache -s  
