language: cpp

matrix:
  include:

    # Ubuntu Linux with glibc using g++-5
    - os: linux
      sudo: false
      compiler: gcc
      cache: ccache
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libwww-perl
            - g++-5
            - libubsan0
            - libeigen3-dev
            - libboost-dev
      before_install:
        - mkdir bin ; ln -s /usr/bin/gcc-5 bin/gcc
      # env: COMPILER=g++-5 SAN_FLAGS="-fsanitize=undefined -fno-sanitize-recover -fno-omit-frame-pointer"
      env: COMPILER="g++-5"

    # Ubuntu Linux with glibc using g++-5, debug mode
    - os: linux
      sudo: false
      compiler: gcc
      cache: ccache
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libwww-perl
            - g++-5
            - libubsan0
            - libeigen3-dev
            - libboost-dev
      before_install:
        - mkdir bin ; ln -s /usr/bin/gcc-5 bin/gcc
      # env: COMPILER=g++-5 SAN_FLAGS="-fsanitize=undefined -fno-sanitize-recover -fno-omit-frame-pointer"
      env:
        - COMPILER="g++-5"
        - EXTRA_CXXFLAGS="-DDEBUG"
      script: echo "Not running any tests for a debug build."

    # Ubuntu Linux with glibc using clang++-3.7, debug mode
    - os: linux
      sudo: false
      compiler: clang
      cache: ccache
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - libwww-perl
            - clang-3.7
            - libstdc++-5-dev
            - libubsan0
            - libeigen3-dev
            - libboost-dev
      before_install:
        - mkdir bin ; ln -s /usr/bin/clang-3.7 bin/gcc
        - export CCACHE_CPP2=yes
        - chmod -R a+x scripts/
      # env: COMPILER=clang++-3.7 SAN_FLAGS="-fsanitize=undefined -fno-sanitize-recover=undefined,integer -fno-omit-frame-pointer"
      env:
        - COMPILER="ccache clang++-3.7 -Qunused-arguments -fcolor-diagnostics"
        - CCACHE_CPP2=yes
        - EXTRA_CXXFLAGS="-DDEBUG"
      script: echo "Not running any tests for a debug build."

    - env: NAME="CPP-LINT"
      install:
      script: scripts/travis_lint.sh
      before_cache:

    - env: NAME="DOXYGEN-CHECK"
      addons:
        apt:
          packages:
            - doxygen
      install:
      script: scripts/travis_doxygen.sh
      before_cache:

  allow_failures:
    - env: NAME="CPP-LINT"
      install:
      script: scripts/travis_lint.sh
      before_cache:

install:
  - export PATH=$PATH:$DSVERIFIER_HOME
  - chmod a+x regression/run-all.sh
  - make bmc-download
  - chmod -R a+x model-checker/

script:
  - make && cd regression/ && ./run-all.sh
  
before_cache:
  - ccache -s 
