language: cpp

sudo: false

cache:
  - ccache

os:
  - linux

addons:
  apt:
    packages:
      - libwww-perl

compiler:
  - gcc
  
matrix:
  include:
    # gcc
    - env: CONF=release ARCH=x86    CXX11=ON
      compiler: gcc
    - env: CONF=release ARCH=x86_64 CXX11=ON
      compiler: gcc
    - env: NAME="CPP-LINT"
      install: chmod -R a+x scripts/
      script: scripts/travis_lint.sh
      before_cache:    
    #- env: NAME="DOXYGEN-CHECK"
    #  addons:
    #    apt:
    #      packages:
    #        - doxygen
    #  install: chmod -R a+x scripts/
    #  script: scripts/travis_doxygen.sh
    
  allow_failures:
    - env: NAME="CPP-LINT"
      install: chmod -R a+x scripts/
      script: scripts/travis_lint.sh
      before_cache:

env:
  global:
    - DSVERIFIER_HOME=$PWD
   
before_install:
  -  add-apt-repository -y ppa:ubuntu-toolchain-r/test
  -  apt-get -qq update
  -  apt-get -qq install g++-4.9 gcc-4.9
  -  update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 60
  -  update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60
  -  apt-get -qq update
  -  apt-get install libeigen3-dev -y
  -  apt-get install libboost-dev -y
  -  apt-get install python2.7
  -  apt-get install libffi-dev libssl-dev

install:
  - export PATH=$PATH:$DSVERIFIER_HOME
  - chmod a+x regression/run-all.sh
  - make bmc-download
  - chmod -R a+x model-checker/

script:
  - make && cd regression/ && ./run-all.sh
  
before_cache:
  - ccache -s 
